export const CLIENT_LOGOS = [
  { name: "Discovery Engineering", src: "/assets/logos/discovery-engineering.png", width: 400, height: 131 },
  { name: "Excol Taxes & Bookkeeping", src: "/assets/logos/excol.png", width: 400, height: 126 },
  { name: "Gutierrez Construction", src: "/assets/logos/gutierrez-construction.png", width: 400, height: 284 },
  { name: "Injury Consulting", src: "/assets/logos/injury-consulting.png", width: 400, height: 118 },
  { name: "Lone Star Ranch Land", src: "/assets/logos/lone-star-ranch-land.png", width: 400, height: 99 },
  { name: "Miami ATV Rentals", src: "/assets/logos/miami-atv-rentals.png", width: 333, height: 400 },
  { name: "Miranda Mortgage Denver", src: "/assets/logos/miranda-mortgage-denver.png", width: 400, height: 165 },
  { name: "Mixtan Stucco", src: "/assets/logos/mixtan-stucco.png", width: 400, height: 177 },
  { name: "Paint Innovators", src: "/assets/logos/paint-innovators.png", width: 400, height: 246 },
  { name: "Petrucci Engineering Consultants", src: "/assets/logos/petrucci-engineering-consultants.png", width: 400, height: 145 },
  { name: "Pivotal Media Partners", src: "/assets/logos/pivotal-media-partners.png", width: 400, height: 161 },
  { name: "Playbook UX", src: "/assets/logos/playbook-ux.png", width: 400, height: 87 },
  { name: "Prodigy Development Center", src: "/assets/logos/prodigy-development-center.png", width: 398, height: 400 },
  { name: "Radiant Results", src: "/assets/logos/radiant-results.png", width: 400, height: 400 },
  { name: "SIQ", src: "/assets/logos/siq.png", width: 400, height: 156 },
  { name: "Snowsports Expert and Consulting", src: "/assets/logos/snowsports-expert-consulting.png", width: 400, height: 126 },
  { name: "SSP Vehicle Litigation Services", src: "/assets/logos/ssp-vehicle-litigation.png", width: 400, height: 237 },
  { name: "Test Drive Tech", src: "/assets/logos/test-drive-tech.png", width: 400, height: 181 },
  { name: "Thrive Work Wear", src: "/assets/logos/thrive-work-wear.png", width: 400, height: 202 },
  { name: "TSMD", src: "/assets/logos/tsmd.png", width: 400, height: 400 },
  { name: "Vision Cleaners", src: "/assets/logos/vision-cleaners.png", width: 400, height: 116 },
  { name: "Widget Studios", src: "/assets/logos/widget-studios.png", width: 400, height: 62 },
  { name: "Wrecken Electric", src: "/assets/logos/wrecken-electric.png", width: 400, height: 75 },
  { name: "Your Paint Guy", src: "/assets/logos/your-paint-guy.png", width: 400, height: 400 },
] as const;
