<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:sm="http://www.sitemaps.org/schemas/sitemap/0.9" xmlns:xhtml="http://www.w3.org/1999/xhtml">
<xsl:output method="html" encoding="UTF-8" indent="yes"/>
<xsl:template match="/">
<html>
<head>
<title>XML Sitemap</title>
<meta name="robots" content="noindex,follow"/>
<style>
  body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif; margin: 40px; color: #121316; background: #fff; }
  h1 { font-size: 22px; margin-bottom: 8px; }
  p { color: #55565c; }
  a.home { color: #0d3a52; }
  table { width: 100%; border-collapse: collapse; margin-top: 24px; font-size: 13px; }
  th { text-align: left; padding: 10px 12px; border-bottom: 2px solid #e4e4e7; color: #121316; }
  td { padding: 10px 12px; border-bottom: 1px solid #e4e4e7; color: #55565c; vertical-align: top; }
  tr:hover td { background: #f6f6f7; }
  a { color: #0d3a52; text-decoration: none; }
  a:hover { text-decoration: underline; }
  .alt { color: #86868c; }
</style>
</head>
<body>
<h1>XML Sitemap</h1>
<p>Generated by <a class="home" href="/">Precise Wolf Digital</a> — this file is meant for search engines. Contains <xsl:value-of select="count(sm:urlset/sm:url)"/> URLs.</p>
<table>
<tr><th>URL</th><th>Alternates</th><th>Last Modified</th><th>Change Freq.</th><th>Priority</th></tr>
<xsl:for-each select="sm:urlset/sm:url">
<tr>
<td><a href="{sm:loc}"><xsl:value-of select="sm:loc"/></a></td>
<td class="alt">
<xsl:for-each select="xhtml:link">
<xsl:value-of select="@hreflang"/>
<xsl:if test="position() != last()"><xsl:text>, </xsl:text></xsl:if>
</xsl:for-each>
</td>
<td><xsl:value-of select="sm:lastmod"/></td>
<td><xsl:value-of select="sm:changefreq"/></td>
<td><xsl:value-of select="sm:priority"/></td>
</tr>
</xsl:for-each>
</table>
</body>
</html>
</xsl:template>
</xsl:stylesheet>
